name: Build Docker image

on:
    push:
        branches-ignore: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    DOCKER_IMAGE_NAME: jorgev259/squid-qobuz-dl
    DOCKER_REGISTRY_URL: ghcr.io

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                  ref: 'main'

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: false
                  outputs: type=cacheonly
                  tags: |
                      ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:latest
                      ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
